version: '3.8'

services:
  java-app:
    image: java-app
    build:
      context: .
      dockerfile: Dockerfile-java
    ports:
      - "8080:8080"
    depends_on:
      - node-app

  node-app:
    image: node-app
    build:
      context: ./src/main/client
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"